docusaurus.config.js
| Service                  |  documentation portal
| Minor: New Feature?      | adding search bar
| Documentation PR         | n/a
| Any Dependency Changes?  | no
| License                  | AGPL
Integrated Algolia search to the docs portal
=> Add docsearch

docs/FAQ/Background.md, docs/FAQ/General.md, docs/FAQ/Oracles.md, docs/FAQ/_category_.json
| Service                  |  docs
| Fixed Issues?            | n/a
| Patch: Bug Fix?          | n/a
| Major: Breaking Change?  | n/a
| Minor: New Feature?      | n/a
| Documentation PR         | `[skip-ci]`
| Any Dependency Changes?  | n/a
Add FAQ section to the docs portal
=> add FAQ section

docs/Developers/glossary.md
| Service                  | docs
| Fixed Issues?            | -
| Patch: Bug Fix?          | -
| Major: Breaking Change?  | -
| Minor: New Feature?      | -
| Documentation PR         | `[skip-ci]`
| Any Dependency Changes?  |
=> Add additional terms to Glossary

docs/Developers/tutorials/boilerplate.md
Rework boilerplate guide from docs to improve usability and readability
=> Rework boilerplate guide

docs/Developers/tooling.md
Rework Additional Resources Section: use a table format instead of just links and add a description for each resource
=> Rework Additional Resources Section

docs/Developers/contracts.md
Improve readability for IChronicle Interface example within the docs
=> Improve readability

docs/Developers/contracts.md
Add a basic IChronicle Contract Implementation Example, and link to the IChronicle Interface
=> Add IChronicle Contract Implementation Example

docs/hackathons/eth-global-brussels-hackathon.md
Add Bounties for ETHGlobal Brussels and resources
=> Add Bounties ETHGlobal Brussels

docs/hackathons/eth-global-brussels-hackathon.md
Add a 3rd track - Educational track, and the SelfKisser addresses on Base, Arbitrum, and Optimism
=> Add Edu Track and SelfKisser addresses

docs/hackathons/eth-global-brussels-hackathon.md
Add details of Oracle-Reader based on Scaffold- ETH2
=> Add details Oracle-Reader

docs/hackathons/eth-global-brussels-hackathon.md
=> Add GitHub repo for workshop

docs/Intro/dive/offchain.md
- Just updates a typo in documentation
=> fix typo in offchain.md

docusaurus.config.js
=> Add audits to footer

package.json, src/theme/SearchBar.js, yarn.lock
| Service                  | (gofer, spectre, spire etc)
| Fixed Issues?            | Resolves #73
| Patch: Bug Fix?          | No
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes
| Documentation PR         | `[skip-ci]`
| Any Dependency Changes?  | Added `@cookbookdev/docsbot` package
| License                  | AGPL
The AI assistant and co-pilot is trained on all existing Chronicle resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building projects on Chronicle Protocol, acting as an enhanced and streamlined technical documentation search …
=> feat: Cookbook Onboard integration

docs/Developers/testnet.md
Add testnet addresses for the Orcales
=> Add testnet addresses

package-lock.json, package.json, src/theme/SearchBar.js, yarn.lock
Docusaurus project already has a search plugin,  [theme-search-algolia](https://docusaurus.io/docs/api/themes/@docusaurus/theme-search-algolia), so the current search plugin needs to [swizzle](https://docusaurus.io/docs/swizzling), and needs Markprompt added as a standalone component to allow the correct display.
=> Add Markprompt

docusaurus.config.js
Add links to Developers, Validators, and Dashboard sections in the navbar, for easier navigation
=> Add navbar links

docs/Intro/dive/offchain.md, docs/Intro/dive/pushOracle.md, docusaurus.config.js, package.json, yarn.lock
Add @docusaurus/theme-mermaid for diagrams
Created PUSH Oracle diagram + explanation
=> Add PUSH Oracle diagram in Mermaid

docs/Developers/Guides/contracts.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/glossary.md, docs/Developers/start.md, docs/Developers/testnet.md, docs/Developers/tooling.md, docs/Developers/tutorials/Remix.md, docs/Developers/tutorials/boilerplate.md, docs/FAQ/Background.md, docs/FAQ/General.md, docs/FAQ/Oracles.md, docs/Intro/Scribe/scribe.md, docs/Intro/Scribe/scribeOptimistic.md, docs/Intro/dashboard.md, docs/Intro/dive/dive.md, docs/Intro/dive/offchain.md, docs/Intro/dive/onchain.md, docs/Intro/dive/pushOracle.md, docs/Intro/intro.md, docs/Intro/mission.md, docs/Intro/network.md, docs/validators/existing-k8s.md, docs/validators/quickstart.md, docs/validators/troubleshooting.md, docs/validators/upgrading.md
Add SEO to docs pages for better indexing and search results
=> Add SEO to docs pages

docs/Intro/intro.md
Add descriptions for each of the attributes in Intro page
=> Add descriptions for all attributes in Intro

docs/FAQ/General.md, docs/Intro/network.md
- update validator list on the intro page as well as FAQ
=> Update validator list

docs/Developers/testnet.md
=> Add BerachainBartio adresses

docs/Developers/Guides/whitelistAddress.md
- adds SelfKisser addresses on each chain for better visibility and convenience
=> Update whitelisting guide

docs/hackathons/eth-global-sf-hackathon.md
Add ETHGlobal SF guide and bounties to Hackathons section
=> Add SF Guide to Hackathons

docs/Resources/FAQ/General.md, docs/Resources/FAQ/Oracles.md, docs/Resources/FAQ/Points.md
Update FAQ with:
- Chronicle Points section
- types of Oracles supported
- Oracle threshold update 
https://app.shortcut.com/chronicle-labs/story/8212/create-a-manual-for-the-chronicle-points-users
=> Update FAQ Section

docs/Developers/testnet.md
Remove MATIC Oracles from docs
=> Remove matic oracles from docs

docs/validators/existing-k8s.md, docs/validators/quickstart.md, docs/validators/upgrading.md
- updates validator docs to pin to the latest helm chart version
=> udpate docs for latest validator chart version

docs/validators/troubleshooting.md
- adds steps to recreate user-space kubeconfig
=> Adds recreation of kubeconfig file to troubleshooting

docusaurus.config.js
Update announcement bar for ETHGlobal SF
=> Update announcement bar

docs/Developers/testnet.md
Add POL Oracles to docs and remove MATIC ones
=> Add POL Oracles

docs/Intro/dive/rwaOracle.md, docs/Intro/dive/yieldRateOracle.md
- what is it
- when it is used
- additional function `getAPR()`
=> Add Yield Oracle to docs

docs/Developers/start.md
Update getting started guide with dev resources links
=> Update getting started

docusaurus.config.js
Add newsletter subscribe link in footer
=> Add newsletter subscribe link

docs/Developers/tutorials/Remix.md
Add SelfKisser addresses to Remix guide
=> Add SelfKisser addresses

docs/Developers/Guides/readingFromOracles.md, docs/hackathons/eth-global-bangkok-hackathon.md
Add additional resources for ETHGlobal hackathon
=> Add additional resources for the hackathon

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/tutorials/Remix.md, docs/Resources/FAQ/General.md
Add SelfKisser on Superseed Sepolia to docs
=> Add SelfKisser on Superseed Sepolia

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/testnet.md, docs/Developers/tutorials/Remix.md
- Add Additional Testnet addresses for Corn and Superseed
=> Add Additional Testnet addr

docs/Intro/intro.md, docs/Products/productsOverview.md, src/components/LinkButton/index.js, src/components/LinkButton/styles.module.css, src/pages/index.js, src/pages/index.module.css, src/pages/markdown-page.md, yarn.lock
Add start page to docs and sub-categories
=> Add start page to docs

docs/Developers/Guides/Chronicle Pull Oracles/GettingStarted.md, docs/Developers/Guides/Chronicle Pull Oracles/authenticate.md
This adds await to `signAuthToken` and function parameter descriptions.
=> Pull oracles fixes

docs/Resources/Community.md, docs/Resources/FAQ/_category_.json, docs/Resources/UseCases.md
Add section with example use cases under resources
=> Add use cases section

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/testnet.md, docs/Developers/tutorials/Remix.md, docs/Resources/FAQ/General.md
Add Plume Network to docs:
- SelfKisser address in guides
- update chains no
- addresses on testnet
=> Add Plume Network to docs

docs/Developers/tutorials/Remix.md, src/components/Button/index.js
Add Remix button for OracleReader example interaction
=> Add Remix button

docs/Developers/tooling.md
Add additional dev resources and their corresponding GitHub pages
=> Add additional dev resources

docs/Developers/testnet.md
Fix small indentation breaking description formatting
=> Fix small indentation

docs/Products/DeFiOracle/DeFiOracle.md, docs/Products/DeFiOracle/yieldRateOracle.md, docs/Products/productsOverview.md, docs/Products/verifiedAssetOracle.md, src/pages/index.js
Restructure Products Section to describe the main 2 categories of products: DeFi Oracles and VOA Oracle
- describe the different type of data that can be delivered by DeFi Oracles
=> Update Products Section

docs/Intro/feeds.md
create section in the docs on oracle types
- Market Based Oracle
[METH/ETH](https://chroniclelabs.org/dashboard/oracle/METH/ETH?blockchain=MANTLE&txn=0x0942ab3efafd5a04f9a97215a02b67388ede279f1e212dbf7a2a5dd477c40554&contract=0xBFE568Ea8f6bDFFe7c03F83dC8348517f8E7010A)
- Fundamental Based Oracle
[SUSDS/USD](https://chroniclelabs.org/dashboard/oracle/SUSDS/USD?blockchain=ETH&txn=0x0029c6679f8ffbfabac2bce41a60a372f2fdd3a72de94ca0b29a89531e13774c&contract=0x496470F4835186bF118545Bd76889F123D608E84)
- Hybrid Oracle
[WSTETH/ETH](https://chroniclelabs.org/dashboard/oracle/WSTETH/ETH?blockchain=ZKSYNC&txn=0xe2c51f7a044c95048287b542332ff6131ce53abc9ebee6faea513eab18ffc4e7&contract=0x700eAe32715D29443e1ff8EE89b0ba333BaedC0b)
=> Add types of oracles section

docs/Developers/testnet.md
Adding Testnet addresses for Monad
=> Add Monad addresses

docs/Developers/testnet.md
Add newly generated addresses after script fix
=> Add new addresses generated by script

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/tutorials/Remix.md
Adding Monad selfKisser address to guides
=> Adding Monad selfKisser

docs/Resources/FAQ/Oracles.md
Fix link that was pointing to Morpho's docs
=> Fix wrong link

docs/Resources/Utils.md
Add Utils page including faucet info for diff chains and RPCs
=> Add Utils page

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/tutorials/Remix.md
Add selfKisser address for Unichain in the docs
=> Add selfKisser address for Unichain

docs/Intro/Scribe/scribeOptimistic.md
=> Update Scribe Optimistic page

docs/validators/existing-k8s.md, docs/validators/quickstart.md
- Add note about running a Chronicle validator being a permissioned process 
- Mention the targeted audience for the _Validators_ part of the docs
=>  Add note about running a validator

docs/Intro/Scribe/scribeOptimistic.md, docs/Products/DeFiOracle/DeFiOracle.md, docs/Resources/FAQ/Background.md, docs/Resources/FAQ/Oracles.md
| Service                  | (gofer, spectre, spire etc)
| Fixed Issues?            | fix document typo
| Patch: Bug Fix?          | no
| Major: Breaking Change?  | no
| Minor: New Feature?      | no
| Documentation PR         | `[skip-ci]`
| Any Dependency Changes?  |
| License                  | AGPL
- Checked every markdown files in the docs and found and fixed obvious typos that changed the meaning in context. Hope this helps.
=> doc: fix typos

docs/Resources/FAQ/General.md
add latest chains integrated to the FAQ list
=> Update total number chains integrated

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/tutorials/Remix.md
Replace Plume Devnet to Testnet for selfKisser
=> Add Plume Testnet

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/tutorials/Remix.md
Replace Bartio with Bepolia for selfKisser
=> Add selfKisser Bepolia

docs/Developers/testnet.md
Add new Testnet addresses (Plume + new assets)
=> Add new Testnet addresses

docs/Resources/Audits.md
Add audits page for better discoverability. The current link from footer does not get indexed by search.
=> Add audits page

docusaurus.config.js, package.json, yarn.lock
Add llm.txt plugin to generate the llm.txt file for LLMs parsing of docs
=> Add llm.txt plugin

docs/Intro/Scribe/scribeOptimistic.md
Add details on challenger for Scribe Optimistic
=> Add details on challenger

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/testnet.md, docs/Developers/tutorials/Remix.md, docs/Resources/FAQ/General.md, docs/Resources/Utils.md, docs/hackathons/Previous/eth-global-brussels-hackathon.md, docs/hackathons/Previous/eth-global-sf-hackathon.md, docs/hackathons/eth-global-bangkok-hackathon.md
Remove Polygon zkEVM occurences form docs
=> Remove Polygon zkEVM

docs/Developers/Guides/readingFromOracles.md, docs/Developers/Guides/whitelistAddress.md, docs/Developers/tutorials/Remix.md, docs/Resources/FAQ/General.md
- add selfKisser to guides
- update list of chains supported
=> Add Plasma to docs
